#!/bin/bash
#
#BSUB -J "###NAME###"
#BSUB -P gpu-service
#BSUB -q yuangpu
#BSUB -e errorsclassification/###NAME###.errors.%J
#BSUB -o outputsclassification/###NAME###.output.%J
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[ngpus_excl_p=1]"
#BSUB -W 50:00
#BSUB -u shan.raza@icr.ac.uk
module load anaconda/3/4.3.0
module load gcc/4.9.3
source activate tfDavrosGPU1p4
cd /mnt/scratch/users/molecpath/sraza/scripts/MyCodes/TracerX/classification/20171019-SCCNNClassifier
python Generate_Output_Davros.py "###DIRNAME###" "###NAME###"